#include "upgrade_registry.h"
const RogueUpgradeDef rogue_upgrades[24] = {
    { "power", "Power", "Deal 8% more damage.", 35, 3, 0, 8 },
    { "guard", "Thick Skin", "Take 8% less damage.", 40, 3, 1, 8 },
    { "stride", "Long Stride", "Run 6% faster.", 45, 3, 2, 6 },
    { "air", "Air Control", "Move 6% faster in the air.", 50, 3, 3, 6 },
    { "jump", "High Jump", "Jump 5% higher.", 35, 3, 4, 5 },
    { "shield", "Shield Core", "Increase shield capacity by 10%.", 40, 3, 5, 10 },
    { "regen", "Shield Recovery", "Recover shield 8% faster.", 45, 3, 6, 8 },
    { "weight", "Anchor", "Increase weight by 5%.", 50, 3, 7, 5 },
    { "grip", "Strong Grip", "Deal 10% more standard throw damage.", 35, 3, 8, 10 },
    { "reach", "Recovery Window", "Gain 5 frames of ledge invulnerability.", 40, 3, 9, 5 },
    { "stock", "Second Wind", "Gain one stock for the next fight.", 45, 3, 10, 1 },
    { "gold", "Bounty", "Earn 10% more combat gold.", 50, 3, 11, 10 },
    { "score", "Showmanship", "Earn 10% more run score.", 35, 3, 12, 10 },
    { "heal", "Campfire", "Recover 10% damage at rest.", 40, 3, 13, 10 },
    { "launch", "Launcher", "Increase outgoing knockback by 5%.", 45, 3, 14, 5 },
    { "poise", "Poise", "Reduce received knockback by 5%.", 50, 3, 15, 5 },
    { "dash", "Quick Start", "Accelerate on the ground 6% faster.", 35, 3, 16, 6 },
    { "fall", "Feather", "Fall 5% more slowly.", 40, 3, 17, 5 },
    { "landing", "Soft Landing", "Reduce landing lag by 5%.", 45, 3, 18, 5 },
    { "dodge", "Evasion", "Gain 2 frames of dodge invulnerability.", 50, 3, 19, 2 },
    { "vampire", "Victory Snack", "Recover 8% damage after a KO.", 35, 3, 20, 8 },
    { "thorns", "Retaliation", "Return 4% of received damage.", 40, 3, 21, 4 },
    { "discount", "Haggler", "Shop items cost 5% less.", 45, 3, 22, 5 },
    { "first", "Opening Strike", "First hit each stock deals 15% more damage.", 50, 3, 23, 15 },
};
