#ifndef ROGUE_BALANCE_H
#define ROGUE_BALANCE_H
#define ROGUE_UPGRADE_REROLL_BASE 15U
#define ROGUE_UPGRADE_REROLL_STEP 10U
#define ROGUE_SHOP_REROLL_BASE 25U
#define ROGUE_SHOP_REROLL_STEP 15U
#define ROGUE_STARTING_GOLD 50U
#define ROGUE_NORMAL_REWARD 30U
#define ROGUE_ELITE_REWARD 55U
#define ROGUE_BOSS_REWARD 100U
#endif
