"""Author a native relocatable HSD DAT; runtime only loads/drives its JOBJ tree.

All polygons, colors and layout below are original. No retail data is embedded.
Coordinates use a 640x480 orthographic camera. Display lists are 32-byte aligned.
"""
import json
import math
import struct
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]


def generate():
    data = bytearray()
    reloc = []
    roots = []
    nodes = []
    def alloc(size, align=4):
        data.extend(b'\0' * ((-len(data)) % align))
        start = len(data)
        data.extend(b'\0' * size)
        return start
    def put(offset, fmt, *values): struct.pack_into('>' + fmt, data, offset, *values)
    def ptr(offset, target):
        put(offset, 'I', target)
        reloc.append(offset)
    root = alloc(64)
    put(root + 4, 'I', 0x10000000)
    put(root + 32, '3f', 1, 1, 1)
    verts = alloc(48)
    put(verts, '4IBxHI', 9, 1, 1, 4, 0, 12, 0)
    put(verts + 24, 'I', 255)
    def polygon(name, points, color):
        joint, dobj, mobj, mat, pobj = [alloc(n) for n in (64,16,24,20,24)]
        display_size = (3 + 12 * len(points) + 31) & ~31
        display = alloc(display_size, 32)
        put(display, 'BH', 0xA0, len(points))
        for i, (x,y) in enumerate(points): put(display + 3 + i*12, '3f', x, -y, 0)
        put(joint + 4, 'I', 0x40000)
        put(joint + 32, '3f', 1,1,1)
        ptr(joint + 16, dobj)
        ptr(dobj + 8, mobj)
        ptr(dobj + 12, pobj)
        put(mobj + 4, 'I', 0x08002001)
        ptr(mobj + 12, mat)
        data[mat:mat+12] = bytes([255,255,255,255] + list(color) + [255,0,0,0,255])
        put(mat + 12, '2f', 1,0)
        ptr(pobj + 8, verts)
        put(pobj + 12, 'HH', 0, display_size // 32)
        ptr(pobj + 16, display)
        nodes.append((name,joint))
    def panel(name,x,y,w,h,color,bevel=8):
        b=bevel
        polygon(name, [(x+b,y),(x+w-b,y),(x+w,y+b),(x+w,y+h-b),(x+w-b,y+h),(x+b,y+h),(x,y+h-b),(x,y+b)],color)
    panel('background',0,0,640,480,(9,12,28),0)
    polygon('diagonal',[(0,104),(640,69),(640,384),(0,415)],(22,27,63))
    polygon('accent',[(0,118),(640,83),(640,93),(0,128)],(43,52,103))
    panel('route_line',46,35,548,2,(90,101,130),0)
    for i in range(15):
        x=48+i*39
        points=[(x+9*math.cos(a*math.pi/4),36+9*math.sin(a*math.pi/4)) for a in range(8)]
        polygon(f'route_{i}',points,(92,103,133))
    panel('title_rule',18,86,604,2,(98,110,155),0)
    for i in range(3):
        x=20+i*204
        panel(f'focus_{i}',x-3,117,198,126,(246,205,54),11)
        panel(f'card_{i}',x,120,192,120,(107,119,159),9)
        panel(f'card_inner_{i}',x+4,124,184,112,(20,24,46),7)
        panel(f'icon_{i}',x+12,133,31,31,(52,64,107),4)
        panel(f'card_rule_{i}',x+12,176,168,1,(100,111,149),0)
    for i in range(2):
        x=20+i*320
        panel(f'route_focus_{i}',x-3,117,286,126,(246,205,54),11)
        panel(f'route_card_{i}',x,120,280,120,(107,119,159),9)
        panel(f'route_inner_{i}',x+4,124,272,112,(20,24,46),7)
    panel('versus_left',20,260,280,138,(29,46,83),9)
    panel('versus_right',340,260,280,138,(62,31,69),9)
    polygon('vs_slash',[(327,264),(338,256),(315,390),(303,400)],(186,39,50))
    panel('build_rule',18,413,604,2,(98,110,155),0)
    panel('build_panel',16,107,608,298,(16,20,39),10)
    for i,(_,joint) in enumerate(nodes):
        ptr(root+8 if i==0 else nodes[i-1][1]+12,joint)
    roots=[('RogueProgression_joint',root)]
    data.extend(b'\0'*((-len(data))%32))
    symbols=b''
    publics=b''
    for name,offset in roots:
        publics+=struct.pack('>II',offset,len(symbols))
        symbols+=name.encode()+b'\0'
    tail=b''.join(struct.pack('>I',x) for x in reloc)+publics+symbols
    header=struct.pack('>5I4s2I',32+len(data)+len(tail),len(data),len(reloc),len(roots),0,b'HSD0',0,0)
    asset=header+data+tail
    folder=ROOT/'build/assets'
    folder.mkdir(parents=True,exist_ok=True)
    (folder/'RogueUi.dat').write_bytes(asset)
    (folder/'layout.json').write_text(json.dumps({'canvas':[640,480],'joints':[name for name,_ in nodes]},indent=2)+'\n')
    source=['/* Generated by tools/generate_ui.py; original authored native DAT. */', '#include <dolphin/types.h>', 'const unsigned char rogue_ui_dat[] ATTRIBUTE_ALIGN(32) = {']
    source += ['    '+','.join(f'0x{x:02x}' for x in asset[i:i+24])+',' for i in range(0,len(asset),24)]
    source+=['};',f'const unsigned rogue_ui_dat_size = {len(asset)};','']
    (ROOT/'src/platform/melee/ui_asset_data.c').write_text('\n'.join(source))
    header=['#ifndef ROGUE_UI_ASSET_H','#define ROGUE_UI_ASSET_H','extern const unsigned char rogue_ui_dat[];','extern const unsigned rogue_ui_dat_size;','enum RogueUiJoint {']
    header += [f'    ROGUE_UI_{name.upper()} = {i},' for i,(name,_) in enumerate(nodes)]
    header += [f'    ROGUE_UI_JOINTS = {len(nodes)}','};','#endif','']
    (ROOT/'src/platform/melee/ui_asset_data.h').write_text('\n'.join(header))
    print(f'Authored RogueUi.dat: {len(asset)} bytes, {len(nodes)} JOBJ panels, {len(reloc)} relocations')

if __name__=='__main__': generate()

